import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
      <header>
          <nav>
              <div className="logo">
                  <Image src="/image.svg" width="30" alt="home icon" height={200} />
                  <h1>CoC</h1>
              </div>
              <ul id="bar" className="bar">
                  <li></li>
                  <li></li>
                  <li></li>
              </ul>
              <ul className="content-bar" id="content-bar">
                  <li><Link href='/'>Home</Link></li>
                  <li><Link href='/about'>About</Link></li>
                  <li><Link href='/contact'>Contact</Link></li>
              </ul>
          </nav>
      </header>
        {children}
      </body>
    </html>
  );
}
